# SyndX Build Pipeline

trigger:
- main

pool: Azure Pipelines

steps:

  # Install Docker CLI
  - task: DockerInstaller@0
    displayName: 'Install Docker CLI'
    inputs:
      dockerVersion: 'docker-24.0.7'

    # Build the docker image to check if everything is ok
  - script: docker build --target production -t syndx:prod .
    displayName: 'Build docker image'

    # Create docker image artifact
  - script: docker save -o $(Build.ArtifactStagingDirectory)/syndx.tar syndx:prod
    displayName: 'Create docker image artifact'

    # Publish the artifacts folder for release pipeline use
  - task: PublishBuildArtifacts@1
    inputs:
      PathtoPublish: '$(Build.ArtifactStagingDirectory)'
      ArtifactName: 'syndx-build-drop'
      publishLocation: 'Container'