# SyndX Build Pipeline

trigger:
- main

steps:

  # Install Docker CLI
  - task: DockerInstaller@0
    displayName: 'Install Docker CLI'
    inputs:
      dockerVersion: '24.0.7'

    # Build the docker image to check if everything is ok
  - script: |
      pwd
      ls
      docker build --target production -t syndx:prod .
    displayName: 'Build docker image'
    workingDirectory: ./dapp/frontend

    # Create docker image artifact
  - script: |
      pwd
      ls
      docker save -o $(Build.ArtifactStagingDirectory)/syndx.tar syndx:prod
    displayName: 'Create docker image artifact'
    workingDirectory: ./dapp/frontend

    # Publish the artifacts folder for release pipeline use
  - task: PublishBuildArtifacts@1
    inputs:
      PathtoPublish: '$(Build.ArtifactStagingDirectory)'
      ArtifactName: 'syndx-build-drop'
      publishLocation: 'Container'