# SyndX Build Pipeline

trigger:
  branches:
    include:
      - main
  paths:
    include:
      - ./dapp/frontend/*
    exclude:
      - ./dapp/backend/*

steps:

    # Install Docker CLI
  - task: DockerInstaller@0
    displayName: 'Install Docker CLI'
    inputs:
      dockerVersion: '24.0.7'

    # Build the docker image to check if everything is ok
  - script: |
      docker build -t syndx .
    displayName: 'Build docker image'
    workingDirectory: ./dapp/frontend

    # Create docker image artifact
  - script: |
      docker save -o $(Build.ArtifactStagingDirectory)/syndx.tar syndx
    displayName: 'Create docker image artifact'
    workingDirectory: ./dapp/frontend

    # Publish the artifacts folder for release pipeline use
  - task: PublishBuildArtifacts@1
    inputs:
      PathtoPublish: '$(Build.ArtifactStagingDirectory)'
      ArtifactName: 'syndx-build-drop'
      publishLocation: 'Container'